version: '3'

services:
  mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: 'julix'
      MONGO_INITDB_ROOT_PASSWORD: 'secret'
    volumes:
      - './data:/data/db'
    ports:
      - '27017:27017'
  node:
    build:
      context: .
      dockerfile: ./node.Dockerfile
    volumes:
      - './:/app'

  nginx:
    build:
      context: .
      dockerfile: './nginx.Dockerfile'
    ports:
      - '8080:80'
